CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE CHAR(10) NOT NULL
);

CREATE TABLE CLASSES (
    ID SERIAL PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL,
    SCHEDULE VARCHAR(200),
    USER_ID INT REFERENCES USERS (ID)
);

CREATE TABLE FILTERS (
    ID SERIAL PRIMARY KEY,
    DANCE_TYPE VARCHAR(50) NOT NULL,
    TIME CHAR(5),
    USER_ID INT REFERENCES USERS (ID)
);

CREATE TYPE APPLICATION_STATUS AS ENUM (
    'Подана',
    'Розглядається',
    'Затверджена',
    'Відхилена'
);

CREATE TABLE APPLICATION_FORMS (
    ID SERIAL PRIMARY KEY,
    STATUS APPLICATION_STATUS NOT NULL,
    SUBMISSION_DATE DATE NOT NULL,
    USER_ID INT REFERENCES USERS (ID),
    PERSONAL_DATA_ID INT
);

CREATE TABLE PERSONAL_DATA (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    SURNAME VARCHAR(50) NOT NULL,
    CONTACT_DETAILS VARCHAR(200) NOT NULL,
    APPLICATION_FORM_ID INT REFERENCES APPLICATION_FORMS (ID)
);
