name: Data Schema Code Convention

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SQLFluff
      run: pip install sqlfluff

    - name: Run SQLFluff on Data Schema
      run: sqlfluff lint .github/DataSchema.sql --dialect postgres  
