name: Print Software Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Перша робота - перевірка версій на рівні обробки даних
  check-data-processing-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Виведення версії Node.js
        run: node -v
      
      - name: Виведення версії Angular
        run: ng version || echo "Angular CLI не встановлений"

  # Друга робота - перевірка версій на рівні доступу до даних
  check-database-access-version:
    runs-on: ubuntu-latest
    steps:
      - name: Виведення версії MySQL
        run: mysql --version || echo "MySQL не встановлений"
